config/routes.rb
DrawingTracker::Application.routes.draw do

  root to: "projects#index"

  resources :projects

  resources :drawings

  get "/projects/:id/by_status", to: "projects#by_status"

  get "/ready", to: "projects#ready"

end

app/models/area.rb
class Area < ActiveRecord::Base
  attr_accessible :name

  has_many :erection_drawings
end

app/models/drawing.rb
class Drawing < ActiveRecord::Base
  attr_accessible :number, :status, :notes, :footage, :approval_status

  has_paper_trail

  belongs_to :project
  has_many :drawing_histories

  def self.engineering_status
    { "Queue"     => :ready,
      "Detailing" => :in_progress,
      "Approval"  => :approval,
      "Question"  => :question,
      "Returned"  => :ready,
      "Revising"  => :in_progress,
      "Releasing" => :in_progress,
      "Released"  => :finished }
  end

  ENGINEERING_STAGE = self.engineering_status.keys
  APPROVAL_STATUSES = ["Not Approved", "RR", "FAC", "FAS" ]

  def self.by_status(project_id)
    where(project_id: project_id).order(:status)
  end

  def self.add_or_update(params, drawing)
    drawing_query = where(project_id: params[:project_id], number: drawing).all
    if drawing_query.empty?
      footage = params[:footage] || 0
      drawing = create(number: drawing, status: params[:status], notes: params[:notes], approval_status: params[:approval_status] footage: footage)
      # drawing.drawing_histories.create(status: params[:status], notes: params[:notes])
    else
      drawing = drawing_query[0]
      drawing.status = params[:status] unless params[:status].empty?
      drawing.approval_status = params[:approval_status] unless params[:approval_status].empty?
      drawing.notes = params[:notes] unless params[:notes].empty?
      drawing.footage = params[:footage] unless params[:footage].empty?
      drawing.save
      # drawing.drawing_histories.create(status: params[:status], notes: params[:notes])
    end
  end

  def color_status
    self.class.engineering_status[status]
  end
end

app/models/drawing_history.rb
class DrawingHistory < ActiveRecord::Base
  attr_accessible :drawing_id, :notes, :status

  belongs_to :history
end

app/models/project.rb
class Project < ActiveRecord::Base
  attr_accessible :name, :number, :footage

  has_many :drawings
  has_many :project_histories

  validates :footage, presence: true

  def drawings_by_number
    Drawing.where(project_id: id).order(:number).all.
      sort!{|x, y| x.number.to_i <=> y.number.to_i}
  end

  def drawings_by_status
    Drawing.where(project_id: id).order(:status).all
  end

  def number_of_drawings
    number = Drawing.where(project_id: id).all.length
    if number == 0
      "No"
    else
      "(#{number})"
    end
  end

  def detailed_footage
    Drawing.where(project_id: id).map{|d| d.footage || 0 }.inject(:+)
  end

  def percent_in_shop
    #TODO Lots of fixes here due to no validations. Time for validations

    # percent = (Drawing.where(status: "finished", project_id: id).all.length.to_f / Drawing.where(project_id: id).all.length * 100.0).round(2)
    percent = (percent_released / ( Project.find(id).footage || 0 ) * 100.0).round(2)
    if percent.nan?
      0.0
    else
      percent
    end
  end

  def footage_finished
    Drawing.where(status: "Released", project_id: id).map{|d| d.footage || 0 }.inject(:+)
  end

  def no_of_drawings_ready
    number = Drawing.where(status: "Queue", project_id: id).all.length + Drawing.where(status: "Returned", project_id: id).all.length
    if number == 0
      "0"
    else
      "(#{number})"
    end
  end

  def no_of_drawings_question
    number = Drawing.where(status: "Question", project_id: id).all.length
    if number == 0
      "No"
    else
      "(#{number})"
    end
  end

  def percent_released
    Drawing.where(status: "Released", project_id: id).map{|d| d.footage || 0 }.inject(:+).to_f || 0
  end

end

app/models/project_history.rb
class ProjectHistory < ActiveRecord::Base
  attr_accessible :drawings, :status, :notes, :footage, :approval_status

  def self.add_event(params)
    create(drawings: params[:drawings],
           status:   params[:status],
           approval_status:   params[:approval_status],
           notes:    params[:notes],
           footage:  params[:footage])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/drawings_controller.rb
class DrawingsController < ApplicationController

  def show
    @drawing = Drawing.find(params[:id])
  end

  def create
    project = Project.find(params[:project_id])

    project.project_histories.add_event(params)

    drawing_list = Drawingshorthand.decrypt(params[:drawings])

    drawing_list.each do |drawing|
      project.drawings.add_or_update(params, drawing)
    end
    redirect_to project_path(params[:project_id])
  end

  def destroy
    drawing = Drawing.find(params[:id])
    drawing.destroy
    redirect_to project_path(drawing.project_id)
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  def index
    if params[:status]
      status = params[:status]
      # @projects = Project.joins(:drawings).select("projects.*, drawings.project_id, count('a')").merge(Drawing.where(status: status)).group(:name).order("count('a') DESC")
      @projects = Project.joins(:drawings).select("projects.*, drawings.project_id, count('a')").merge( Drawing.where(status: status)).group(:id, '"drawings"."project_id"').order("count('a') DESC")
    else
      @projects = Project.order(:number).all
    end
  end

  def show
    @project = Project.find(params[:id])
    @drawing = Drawing.new
  end

  def new
    @project = Project.new
  end

  def create
    @project = Project.new params[:project]
    if @project.save
      redirect_to projects_path
    else
      flash[:error] = "Footage is a required field"
      redirect_to new_project_path
    end
  end

  def ready
    @projects = Project.joins(:drawings).select("projects.*, drawings.project_id, count('a')").merge( Drawing.where(status: "ready")).group(:id, '"drawings"."project_id"').order("count('a') DESC")
  end

  def by_status
    @project = Project.find(params[:id])
    @drawings = Drawing.by_status(@project)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/drawings_helper.rb
module DrawingsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/drawings/_form.html.erb
<%= form_tag drawings_path do %>
    <%= hidden_field_tag :project_id, @project.id %>
    <%= label_tag :drawings, "Drawings" %>
    <%= text_field_tag :drawings %>
    <%= label_tag :status, "Status" %>
    <%= select_tag(:status, options_for_select(Drawing::ENGINEERING_STAGE), include_blank: true) %>
    <%= label_tag :approval_status, "Approval Status" %>
    <%= select_tag(:approval_status, options_for_select(Drawing::APPROVAL_STATUSES), include_blank: true) %>
    <%= label_tag :notes, "Note" %>
    <%= text_field_tag :notes %>
    <%= label_tag :footage, "Footage" %>
    <%= text_field_tag :footage %>
    <%= submit_tag "Update" %>
<% end %>

app/views/drawings/index.html.erb
<h1>Drawings</h1>

<h3>Erection Drawings</h3>
<% @erection_drawings.each do |drawing| %>
  <p><%= drawing.name %></p>
<% end %>

<h3>Piece Drawings</h3>

app/views/drawings/show.html.erb
<h2><%= link_to "#{@drawing.project.name} (#{@drawing.project.number})", project_path(@drawing.project_id) %></h2>
<br>
<h4><%= "Drawing # #{@drawing.number}" %></h4>
<p><%= "(#{@drawing.footage} ft.)" %></p>
<hr>
<h4>Events</h4>
<br>
<table>
  <tr>
    <th>Status</th>
    <th>Approval</th>
    <th>Note</th>
    <th>Footage</th>
    <th>Date</th>
  </tr>
  <tr>
    <td class="table-column"><%= @drawing.status %></td>
    <td class="table-column"><%= @drawing.approval_status %></td>
    <td class="table-column notes"><%= @drawing.notes %></td>
    <td class="table-column "><%= "#{@drawing.footage} ft. " %></td>
    <td class="table-column "><%= @drawing.created_at.strftime("%b %d, %Y") %></td>
  </tr>
  <% if @drawing.versions.length > 1 %>
    <% @drawing.versions.reverse.each do |version| %>
      <tr>
        <% unless version.event == "create" %>
          <td class="table-column"><%= version.reify.status %></td>
          <td class="table-column"><%= version.reify.approval_status %></td>
          <td class="table-column notes"><%= version.reify.notes %></td>
          <td class="table-column "><%= "#{version.reify.footage} ft."%></td>
          <td class="table-column "><%= version.reify.created_at.strftime("%b %d, %Y") %></td>
        <% end %>
      </tr>
    <% end %>
</table>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DrawingTracker</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<br>
  <div class="container">
    <% flash.each do |name, msg| -%>
      <%= content_tag :div, msg, class: name %>
    <% end -%>
    <nav>
      <ul>
        <li><%= link_to "Projects", root_path %></li>
      </ul>
    </nav>
    <div class="6 columns alpha"></div>
    <div class="8 columns omega">
      <%= yield %>
    </div>
  </div>
</body>
</html>

app/views/projects/_drawings_list.html.erb
<h4>Drawings</h4>
<br>
<table>
  <tr>
    <th>Drawing No.</th>
    <th>Status</th>
    <th>Approval</th>
    <th>Note</th>
    <th>Footage</th>
    <th>Last Updated</th>
  </tr>
  <% project.send(order).each do |drawing| %>
    <tr>
      <td class="table-column <%= drawing.color_status %>"><%= link_to drawing.number, drawing_path(drawing.id) %></td>
      <td class="table-column <%= drawing.color_status %>"><%= drawing.status %></td>
      <td class="table-column <%= drawing.color_status %>"><%= drawing.approval_status %></td>
      <td class="table-column notes <%= drawing.color_status %>"><%= drawing.notes %></td>
      <td class="table-column <%= drawing.color_status %>"><%= "#{drawing.footage || 0} ft." %></td>
      <td class="table-column <%= drawing.color_status %>"><%= drawing.updated_at.strftime("%b %d, %Y") %></td>
      <td class="table-column-delete"><%= link_to "Delete", drawing_path(drawing.id), method: "delete", id: "drawing-delete-#{drawing.id}" %></td>
    </tr>
  <% end %>
</table>

app/views/projects/_stats.html.erb
<p>
  <span id="show-stats">
    <%= "#{project.footage_finished || 0} ft. of #{project.footage} ft. Released #{project.percent_in_shop}% - #{project.no_of_drawings_ready} Drawings Ready - #{project.no_of_drawings_question}  Drawings in Question" %>
  </span>
</p>

app/views/projects/by_status.html.erb
<h2>
  <%= "#{@project.name}  (#{@project.number})" %>
  <span><%= link_to "Project by number", project_path(@project.id)%></span>
</h2>
<%= render partial: "stats", locals: {project: @project}  %>
<h5><%= "Estimated Footage: #{@project.footage || 0} ft." %></h5>
<br>
<h5><%= "Detailed Footage: #{@project.detailed_footage || 0} ft." %></h5>
<hr>
<h4>Events</h4>
<br>
<table>
  <tr>
    <th>Drawings</th>
    <th>Status Change</th>
    <th>Note Change</th>
    <th>Footage Change</th>
    <th>Date</th>
  </tr>
  <% @project.project_histories.each do |event| %>
    <tr>
      <td class="table-column"><%= event.drawings %></td>
      <td class="table-column"><%= event.status || "-" %></td>
      <td class="table-column notes"><%= event.notes || "-" %></td>
      <td class="table-column"><%= "#{ event.footage || 0 } ft."%></td>
      <td class="table-column "><%= event.created_at.strftime("%b %d, %Y") %></td>
    </tr>
  <% end %>
</table>
<br>
<hr>
<%= render partial: 'drawings_list', locals: { project: @project, order: :drawings_by_status }%>
<br>
<%= render partial: 'drawings/form', locals: { project: @project }%>

app/views/projects/index.html.erb
<h2>Tuttle Engineering</h2>

<%= link_to "Add project", new_project_path %>
<br>
<br>
<% @projects.each do |project| %>
  <h4>
    <%= link_to "(#{project.number}) #{project.name}", project, class: "project-list-name" %>
  </h4>
  <%= render partial: "stats", locals: {project: project}  %>
<% end %>

app/views/projects/new.html.erb
<%= form_for @project do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :number %>
  <%= f.text_field :number %>
  <%= f.label :footage %>
  <%= f.text_field :footage %>
  <%= f.submit %>
<% end %>

app/views/projects/ready.html.erb
<h2>Tuttle Engineering</h2>

<%= link_to "Add project", new_project_path %>
<br>
<br>
<% @projects.each do |project| %>
  <h4>
    <%= link_to "#{project.name} (#{project.number})", project, class: "project-list-name" %>
  </h4>
    <p>
      <span class="project-small">
        <%= "#{project.percent_in_shop}% Complete of #{project.number_of_drawings} Drawings - #{project.no_of_drawings_ready} Drawings Ready - #{project.no_of_drawings_question}  Drawings in Question" %>
      </span>
    </p>
<% end %>

app/views/projects/show.html.erb
<h2>
  <%= "#{@project.name}  (#{@project.number})" %>
  <span><%= link_to "Project by status", "/projects/#{@project.id}/by_status" %></span>
</h2>
<%= render partial: "stats", locals: {project: @project}  %>
<h5><%= "Estimated Footage: #{@project.footage || 0} ft." %></h5>
<br>
<h5><%= "Detailed Footage: #{@project.detailed_footage || 0} ft." %></h5>
<hr>
<h4>Events</h4>
<br>
<% if @project.project_histories.empty? %>
  <p>No project events</p>
<% else %>
<table>
  <tr>
    <th>Drawings</th>
    <th>Status Change</th>
    <th>Approval Change</th>
    <th>Note Change</th>
    <th>Footage Change</th>
    <th>Date</th>
  </tr>
  <% @project.project_histories.each do |event| %>
    <tr>
      <td class="table-column"><%= event.drawings %></td>
      <td class="table-column"><%= event.status %></td>
      <td class="table-column"><%= event.approval_status %></td>
      <td class="table-column notes"><%= event.notes %></td>
      <td class="table-column"><%= "#{ event.footage || 0 } ft."%></td>
      <td class="table-column "><%= event.created_at.strftime("%b %d, %Y") %></td>
    </tr>
  <% end %>
</table>
<% end %>
<br>
<hr>
<%= render partial: 'drawings_list', locals: { project: @project, order: :drawings_by_number }%>
<br>
<%= render partial: 'drawings/form', locals: { project: @project }%>